# Generated by Django 6.0.2 on 2026-06-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Ảnh')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách')),
                ('phone_number', models.CharField(max_length=20, verbose_name='SĐT')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách')),
                ('phone_number', models.CharField(max_length=20, verbose_name='SĐT')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('service_type', models.CharField(choices=[('cat_tia', 'Cắt tỉa'), ('bao_duong', 'Bảo dưỡng'), ('lop_tham_co', 'Lợp thảm cỏ')], max_length=20, verbose_name='Loại dịch vụ')),
                ('grass_option', models.CharField(blank=True, choices=[('co_thai', 'Cỏ Thái'), ('co_la_gung', 'Cỏ Lá Gừng')], max_length=20, null=True, verbose_name='Tùy chọn cỏ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn đặt dịch vụ',
                'verbose_name_plural': 'Đơn đặt dịch vụ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên cây')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh đại diện')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh phụ 1')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh phụ 2')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh phụ 3')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Giá (VNĐ)')),
                ('girth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đường kính gốc')),
                ('height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chiều cao')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng / Sẵn sàng giao')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='store.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Cây',
                'verbose_name_plural': 'Cây',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.plant')),
            ],
        ),
    ]
