# Generated by Django 6.0.2 on 2026-05-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='Số lượng tồn kho'),
        ),
    ]
