# Generated by Django 6.0.2 on 2026-05-09 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_plant_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name'], 'verbose_name': 'Cây', 'verbose_name_plural': 'Cây'},
        ),
        migrations.AlterModelOptions(
            name='pruningrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu cắt tỉa', 'verbose_name_plural': 'Yêu cầu cắt tỉa'},
        ),
        migrations.AddField(
            model_name='pruningrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='Tên khách'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='SĐT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.plant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='store.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Đường kính'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='girth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hoành gốc'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chiều cao'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên cây'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Giá (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='pruningrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='pruningrequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên khách'),
        ),
        migrations.AlterField(
            model_name='pruningrequest',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='SĐT'),
        ),
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
