# Generated by Django 6.0.2 on 2026-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách')),
                ('phone_number', models.CharField(max_length=20, verbose_name='SĐT')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('service_type', models.CharField(choices=[('cat_tia', 'Cắt tỉa'), ('bao_duong', 'Bảo dưỡng'), ('lop_tham_co', 'Lợp thảm cỏ')], max_length=20, verbose_name='Loại dịch vụ')),
                ('grass_option', models.CharField(blank=True, choices=[('co_thai', 'Cỏ Thái'), ('co_la_gung', 'Cỏ Lá Gừng')], max_length=20, null=True, verbose_name='Tùy chọn cỏ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn đặt dịch vụ',
                'verbose_name_plural': 'Đơn đặt dịch vụ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Cây', 'verbose_name_plural': 'Cây'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh'),
        ),
    ]
