# Generated by Django 6.0.2 on 2026-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_serviceorder_alter_plant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh 2'),
        ),
    ]
