# Generated by Django 6.0.2 on 2026-05-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_plant_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='stock',
        ),
        migrations.AddField(
            model_name='plant',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh phụ 2'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh phụ 3'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Còn hàng / Sẵn sàng giao'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Đường kính tán'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/', verbose_name='Ảnh phụ 1'),
        ),
    ]
