services:
  db:
    image: postgres:15
    container_name: greenshop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=greenshop_db
      - POSTGRES_USER=vietng
      - POSTGRES_PASSWORD=130804
    ports:
      - "5432:5432"
    networks:
      - greenshop_network
    restart: unless-stopped

  web:
    build: .
    container_name: greenshop_web
    command: gunicorn plant_shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - django_media:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - greenshop_network
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: greenshop_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - greenshop_network

  redis:
    image: redis:7-alpine
    container_name: greenshop_redis
    restart: always
    networks:
      - greenshop_network

  celery_worker:
    build: .
    container_name: greenshop_celery
    command: celery -A plant_shop worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - greenshop_network
    restart: unless-stopped

# ==========================================
# KHAI BÁO Ổ CỨNG VÀ MẠNG TỔNG
# ==========================================
volumes:
  postgres_data:
  django_media:
  caddy_data:     
  caddy_config:

networks:
  greenshop_network:
    driver: bridge