services:
  db:
    image: postgres:15
    container_name: greenshop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=greenshop_db
      - POSTGRES_USER=vietng
      - POSTGRES_PASSWORD=130804
    ports:
      - "5432:5432"
    networks:
      - greenshop_network
    restart: unless-stopped

  web:
    build: .
    container_name: greenshop_web
    command: gunicorn plant_shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - django_media:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - greenshop_network
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: greenshop_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - greenshop_network

  redis:
    image: redis:7-alpine
    container_name: greenshop_redis
    restart: always
    networks:
      - greenshop_network

  celery_worker:
    build: .
    container_name: greenshop_celery
    command: celery -A plant_shop worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - greenshop_network
    restart: unless-stopped

  # ==========================================
  # KHỐI GIÁM SÁT HỆ THỐNG (DEVOPS)
  # ==========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: greenshop_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - greenshop_network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: greenshop_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - greenshop_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: greenshop_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - greenshop_network
    restart: unless-stopped

# ==========================================
# KHAI BÁO Ổ CỨNG VÀ MẠNG TỔNG
# ==========================================
volumes:
  postgres_data:
  django_media:
  caddy_data:     
  caddy_config:
  prometheus_data:
  grafana_data:   # Thêm ổ cứng lưu cấu hình biểu đồ của Grafana

networks:
  greenshop_network:
    driver: bridge