name: Auto Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and update code 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/GreenShop---Tree-Selling-Shop
            
            git pull origin main
            
            docker-compose down --remove-orphans
            
            docker rm -f greenshop---tree-selling-shop_web_1 || true
            
            docker-compose up -d --build
            
            docker-compose exec -T web python manage.py migrate
            
            docker-compose exec -T web python manage.py collectstatic --noinput